# Generated by Django 4.2.7 on 2026-04-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('pressure', models.FloatField()),
                ('prediction', models.CharField(choices=[('Healthy', 'Healthy'), ('At Risk', 'At Risk'), ('Failing', 'Failing')], max_length=20)),
            ],
        ),
    ]
