# Generated by Django 4.2.7 on 2026-04-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinedata',
            old_name='pressure',
            new_name='air_temperature',
        ),
        migrations.RenameField(
            model_name='machinedata',
            old_name='temperature',
            new_name='process_temperature',
        ),
        migrations.RenameField(
            model_name='machinedata',
            old_name='vibration',
            new_name='rotational_speed',
        ),
        migrations.AddField(
            model_name='machinedata',
            name='tool_wear',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinedata',
            name='torque',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='prediction',
            field=models.IntegerField(choices=[(0, 'No Failure'), (1, 'Machine Failure')]),
        ),
    ]
