# Generated by Django 4.2.7 on 2026-04-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_pressure_machinedata_air_temperature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinedata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='machinedata',
            name='air_temp_rolling_std_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='air_temp_trend_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='air_temp_velocity_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='proc_temp_trend_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='speed_rolling_min_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='torque_rolling_max_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='torque_trend_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='wear_cumulative',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='wear_trend_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='wear_velocity_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='prediction',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='machinedata',
            index=models.Index(fields=['-timestamp'], name='core_machin_timesta_269859_idx'),
        ),
    ]
